# -------------------------------------------------------------------
# sealed-secrets values
# Chart version pinned at install time: 2.18.0
# -------------------------------------------------------------------

fullnameOverride: sealed-secrets-controller

webhooks:
  tlsSecretName: sealed-secrets-tls

rbac:
  create: true
  createClusterRole: false
  createClusterRoleBinding: false

  serviceProxier:
    create: false
    bind: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
